apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saas-frontend
  template:
    metadata:
      labels:
        app: saas-frontend
    spec:
      containers:
      - name: saas-frontend
        image: your-dockerhub-username/saas-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: saas-frontend-service
spec:
  selector:
    app: saas-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
